ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.omie.ApplicationKt.module ]
    }
}
ktor {
  rabbitmq {
    uri = "amqp://guest:guest@localhost:5672"
    defaultConnectionName = "default_connection"
    dispatcherThreadPollSize = 4
    connectionAttempts = 10
    attemptDelay = 5
    tls {
      enabled = false
    }
  }
}

omie {
  api-prod {
    base-url = "https://app.omie.com.br"
    uri = "/api/v1/financas/contareceber/"
    key = ${?OMIE_API_KEY_PROD}
    secret = ${?OMIE_API_SECRET_PROD}
  }
  api-sandbox {
    base-url = "https://app.omie.com.br"
    uri = "/api/v1/financas/contareceber/"
    key = ${?OMIE_API_KEY_DEV}
    secret = ${?OMIE_API_SECRET_DEV}
  }
}

redis {
  url = "redis://localhost:6379"
}