ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
}

rabbitmq {
    host = "localhost"
    host = ${?RABBITMQ_HOST}
    port = 5672
    port = ${?RABBITMQ_PORT}
    username = "guest"
    username = ${?RABBITMQ_USERNAME}
    password = "guest"
    password = ${?RABBITMQ_PASSWORD}
    virtualHost = "/"
    virtualHost = ${?RABBITMQ_VIRTUAL_HOST}

    queues {
        loteContaReceberOmie = "bowe-dev-lote-conta-receber-omie"
        gerarFatura          = "bowe-dev-gerar-fatura"
        errorFatura          = "bowe-dev-error-fatura"
    }
}

omie {
    api-prod {
        base-url = "https://app.omie.com.br"
        uri      = "/api/v1/financas/contareceber/"
        key      = ${?OMIE_API_KEY_PROD}
        secret   = ${?OMIE_API_SECRET_PROD}
    }
    api-sandbox {
        base-url = "https://app.omie.com.br"
        uri      = "/api/v1/financas/contareceber/"
        key      = ${?OMIE_API_KEY_DEV}
        secret   = ${?OMIE_API_SECRET_DEV}
    }
}

redis {
    url = "redis://localhost:6379"
    url = ${?REDIS_URL}

    idempotency {
        ttlSeconds = 86400
        ttlSeconds = ${?IDEMPOTENCY_TTL_SECONDS}
    }
}